require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
